name: Sobollo
author: CareFran
description: A simple tool to sync GitHub issues to Notion.
branding:
  color: light-blue
  icon: activity
inputs:
  repo:
    description: "The GitHub repository name."
    required: true
  NOTION_API_KEY:
    description: "The Notion API key."
    required: true
  NOTION_DATABASE_ID:
    description: "The ID of the Notion database."
    required: true
  GITHUB_TOKEN:
    description: "GitHub token for accessing repositories and GitHub Projects status (recommended for full functionality)"
    required: false
  PROJECT_TOKEN:
    description: "Personal Access Token with project permissions (alternative to GITHUB_TOKEN)"
    required: false
  include_pull_requests:
    description: "Whether to include Pull Requests in sync (true/false)"
    required: false
    default: "false"
  project_name:
    description: "GitHub Projects v2 project name to sync status from (optional, defaults to first available project)"
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
