name: Sync Issues to Notion

on:
  issues:
    types: [opened, edited, deleted, reopened, closed]
  schedule:
    - cron: '0 5,23 * * 0-4'  # 平日JST8時 (UTC前日23時)
  workflow_dispatch:

jobs:
  sync-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Notion
        uses: carefran/soborlo@main
        with:
          repo: ${{ github.repository }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
          include_pull_requests: "true"
